README.md

The documentation mistakenly says that Rails 4 is required, when in fact Rails 5.0.x is supported.

Update supported Rails version

---

template-test/ci-run.sh
template.rb
variants/accessibility/Gemfile.rb
variants/frontend-base/bin/sass-lint
variants/frontend-base/config/template.rb
variants/frontend-base/sass-lint.yml
variants/frontend-base/template.rb

This base variant sets up webpacker the way we like it `app/frontend` instead of `app/assets` and SASS-lint (including CI).
I have mixed feelings about including sass-lint.yml in the template. Should we pull it in from rabid-dotfiles?

Add variant: frontend-base

---

.dockerignore
Dockerfile
docker-compose.yml
template.rb

Adds Dockerfiles to generated projects.
I've done a bunch of research and tried to build in all the optimisations and best practises so that these dockerfiles can be reused as much as possible between projects (the advantage of encouraging similar Dockerfiles is it allows some layers to be cached).
Best practises:
* Volumes store node modules and bundled gems (this means that the image doesn't need to be rebuilt just because a gem dependency or NPM package is added)
* Image sets up containers to run as a `deploy` user (non-root)
* Always pulls from `ruby:latest` rather than locking to a version (Gemfile and/or .ruby-version _can_ still be used to restrict to a Ruby version)
* `RUN` commands are ordered and structured to encourage Docker to cache layers. 
* We clean up apt once we're done …

Add reference Dockerfiles

---

.prettierignore
.prettierignore.tt
.stylelintignore
.stylelintignore.tt
.stylelintrc.js
package.json
variants/frontend-base/template.rb
variants/frontend-foundation/app/frontend/foundation/base/typography.scss
yarn.lock

sass-lint is deprecated so we are moving to stylelint. Closes issue #27. This is just a first pass - happy to make changes.

Replace sass-lint with stylelint

---

app/controllers/application_controller.rb.tt
app/template.rb
example.env.tt

Adds `http_basic_auth` to the generated `ApplicationController`. I felt that using a template was more appropriate here than gsubbing into the file, since we needed to define a private method and a before action hook.
This method is used by several Ackama projects, so is just being formalised here. It uses the presence of environment variables to determine whether to enable HTTP basic authentication for an application or not. This makes it easy to selectively enable auth, e.g. using `heroku config:set`.

Resolves Issue #32: Add basic authentication helper method to application controller

---

template.rb

A range of improvements to the dev experience with the git parts of Rails app generation:
1. Stop pushing after the app is generated. Let the dev choose when to do that (resolves #22)
2. Fix an issue where a git repo with no commits fails and prevents the initial commit from being written
3. Extend the git commit message to add a pretty-printed hash of the options used to generate the Rails application to the commit message description, for example:
```
commit 64923198f65382faa0ec5be50fe4c2a8a423e81e (HEAD -> master)
Author: Josh McArthur <joshua.mcarthur@gmail.com>
Date:   Wed Dec 11 16:14:07 2019 +1300
Initial commit
Project generated with options:
{"skip_namespace"=>false,
"ruby"=>"/home/josh/.asdf/installs/ruby/2.6.3/bin/ruby",
"database"=>"postgresql",
"skip_gemfile"=>false, …
```

Resolve Issue #22: Improve experience with git commands

---

.travis.yml

We've had some discussion of automatically running the rails-template test suite regularly to ensure that any changes in the wider ecosystem do not break our template. Once a month seems like a good balance of catching issues early without over-building, so I have set this up in Travis. They have a neat option to only do a build if there hasn't been one in the preceding 24 hours, so I've also enabled this.
We can't schedule builds using .travis.yml, so document the presence of scheduled builds in the Travis YML file

Scheduled Travis builds

---

rubocop.yml.tt

The warning was:
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
🤷‍♂ Rubocop changed its mind about where this rule should be categorised I guess

Fix rubocop warning

---

bin/ci-run

`$ignore` is empty in most cases which was causing bundle-audit to not
run. This application does not have any CVEs that it needs to ignore so
I have removed the flag.

Fix bug where bundle-audit was not running properly

---

README.md.tt
public/template.rb

See https://securitytxt.org/ for details. Fixes #63 .

Add security.txt to allow security researchers to contact us

---

README.md.tt
config/environments/production.rb

Fixes issue #64 . Codecare finds this very useful when we need to temporarily turn up logging to diagnose an issue.

Allow log level to be set by LOG_LEVEL env var in production-like envs

---

README.md
README.md.tt
config/database.example.yml.tt

This change allows Rails to be run in staging or production mode locally. This is necessary when debugging asset pre-compilation for production environments.
I have also documented how to actually run rails in prod locally in the generated `README.md` which will hopefully be useful for newer players

Allow running Rails in production modes locally

---

app/assets/stylesheets/application.scss
app/template.rb
app/views/layouts/application.html.erb.tt
variants/frontend-base/app/frontend/stylesheets/_elements.scss
variants/frontend-base/app/frontend/stylesheets/application.scss
variants/frontend-base/app/template.rb
variants/frontend-base/config/template.rb
variants/frontend-base/template.rb

This change makes loading images, SCSS and JS via Webpacker the default (encouraged) way to handle assets in the generated Rails app.
As much as I don't want to go messing with a system that works (i.e. handling SCSS and images in the asset pipeline), there are some things we want to do for performance e.g. automatically running `imageoptim` aon images, that will be a lot easier to land in Webpacker so I think we should make the break away from the asset pipeline for new Rails apps.
I have created https://github.com/eoinkelly/temp-demo-rails-template-output which contains the Rails app generated by this branch. 
The following describes everything you need to do to test this branch locally:
```bash
cd /tmp
git clone git@github.com:ackama/rails-template.git
cd rails-template
git checkout …
```

Start using Webpacker for images and SCSS

---

config/environments/production.rb

This typically happens on Heroku deployments which do not (yet) use a CDN.
This came up pretty regularly in my Lighthouse experiments so I thought we should fix it. Rails asset precompilation (whether through the old sprockets or newer webpacker methods) adds a unique fingerprint to all asset names e.g. `application.css` becomes something like `application. 2780cef1a5b202b2f5823863ca7d360f79cfa29f238ebc06cde7d3a5e60bac3c.css` - the fingerprint is calculated based on the contents of the file so it will change if the file changes. This allows us to set cache control headers which allow proxies/browser to cache assets for up to 1 year because if the asset does change the URL to it will also change and thereby "bust" the cache.

Set appropriate caching headers when Rails serves assets in production

---

spec/rails_helper.rb

/dev/shm is a filesystem device that on Linux systems is guaranteed to be tmpfs - in memory, not written to disk. The same guarantee is not true of `/tmp`, which is where files are typically stored.
Chrome prefers /dev/shm by default for the performance improvement on systems that have a tmp directory that is written to disk, however /dev/shm is limited by the available memory.
Within a Docker container, `/dev/shm` is usually set to 64mb. This is large enough for Chrome to use it, but small enough that it can lead to an out-of-memory type error when Chrome is rendering a large page - e.g. something with a lot of JS, maps, complex UI - that sort of thing.
We disable `/dev/shm` here, as it universally makes Chrome more stable, but has an especially beneficial effect to Chrome running inside …

Disable /dev/shm usage in Chrome

---

README.md.tt
config/environments/production.rb

This change defaults `force_ssl` to being true but allows you to disable
it by setting `RAILS_FORCE_SSL=false` in the env. Running Rails without
forcing SSL is useful when running in production mode locally to debug
asset precompiles etc.

Production envs should default to force_ssl being on

---

overcommit.yml

Rubocop periodically releases new cops. If these cops are not configured
in your .rubocop.yml (or some parent .rubocop.yml) then Rubocop tells
you in its output and this output causes overcommit to fail with a false
positive.

Stop overcommit from failing when Rubocop warns about new cops

---

config/template.rb

ActiveStorage defaults to not setting a `Cache-Control` header so any files served by it will never be cached by the Browser. I think that in most cases we do want caching on this. Sing out if you disagree.
Below is an example of the `config/storage.yml` that gets created **after** this change.
```yaml
ttest:
service: Disk
root: <%= Rails.root.join("tmp/storage") %>
local:
service: Disk
root: <%= Rails.root.join("storage") %>
```

Add default config for cache-control on ActiveStorage uploads

---

app/template.rb
config/secrets.example.yml
example.env.tt

This address is uses in a few places in most real apps e.g.
* ActionMailer (as seen in this change)
* Devise
* Transactional email sending services e.g. Mandrill, Sendgrid
so it is useful to have a single place to change it.
@joshmcarthur mentioned in the conversation on PR #57 that this was a default he used on some apps and I think it's useful enough to be a default for all templates. If/when this change lands I can update PR #57 to us the value from secrets.

Load default email 'From' address from environment variable

---

spec/spec_helper.rb

This configuration allows RSpec to store the status of the last unsuccessful test run in a persistence file, allowing the next run to add the `--only-failures` flag to skip straight to the previously-failed example.

Configure RSpec's 'example_status_persistence_file_path'

---

Gemfile.tt
README.md.tt
config/initializers/health_checks.rb
config/initializers/lograge.rb
config/template.rb
spec/requests/health_checks_spec.rb

Sets up health checks using [OkComputer](https://github.com/sportngin/okcomputer), which is a really nice framework for declaring and checking health checks.
The configuration as default:
* Checks that the app is running
* Checks that the database can be connected to
* Checks what version of the app is running (as long as it is a deployed environment, otherwise this check fails)
* Secures the health check with basic auth if credentials are configured
* Logs health check status to the Rails logger (this just makes it easier to get a healthcheck snapshot while tailing the logs)
Additionally, I have left checks that I set up for a client project in place, but commented out:
* Mailing checks that ActionMailer is configured and that SMTP can be connected to with the provided details
* Redis …

Provision and configure default health checks

---

overcommit.yml

* Rubocop warns if it has cops that you have not configured in the YAML
* Rubocop warns if your YAML config mentions cops it does not recognise
* Overcommit (by default) fails if rubocop outputs any warning that it can't parse
This means that overcommit will fail (due to unrecognised warning output
from rubocop) unless the rules configured in your `.rubocop.yml`
**exactly match** the rules that the specific version of rubocop in the
app knows about.
The problem is that we have a single shared `.rubocop.yml` shared
between many apps on many different versions of rubocop and it's not
feasible to keep rubocop updated to the latest version for all apps -
these updates sometimes require code changes and this work would quickly
overwhelm our support team.
Change how rubocop is invoked in …

Rubocop warnings about unrecognised cops in config breaks overcommit

---

config/initializers/content_security_policy.rb
config/template.rb
spec/requests/content_security_policy_header_spec.rb
variants/devise/template.rb
variants/frontend-base/template.rb

Fixes #90 
The default policy is very strict but the initializer includes some examples of how to loosen it for common scenarios e.g. google fonts, google analytics. Feedback welcome.
* I removed the inline styles from the temporary devise UI we create because they don't provide enough value to enable inline styles in the CSP.
* Webpacker is now creating a separate CSS file in development. This stops it trying to dynamically create `<style>` blocks in the DOM so we don't have to allow that in CSP either.

Add content security policy

---

variants/frontend-base/template.rb

This is failing just the devise template in #105.
The option itself has been [removed](https://github.com/rails/webpacker/pull/2518) in webpacker v5.1.

fix: ensure `check_yarn_integrity` is always `false`

---

variants/devise/spec/system/user_sign_in_feature_spec.rb

The remember_me cookie expiry is in UTC so we need to compare it with
whatever date corresponds to this moment in UTC (not in our local
timezone)
This bug only appears if you change the app's default timezone which we usually do.

Rememberable cookie spec was not accounting for Timezones correctly

---

bin/setup

Instead, Bundler.with_original_env was introduced. This doesn't clean
the environment of bundler entirely, but resets the bundler environment
to the state before the current process was started.
There's however some specific cases where the good old Bundler.clean_env behavior can be useful.
For example, when testing Rails generators, you really want an environment where bundler is out of the picture.
For these situations, Bundler.with_unbundled_env was introduced.
I believe for our use case, bin/setup commands, with_original_env is
what we are after.
In other words:
`Bundler.with_original_env` = reset to how things were before you ran this command
`Bundler.with_unbundled_env` = temporarily forget that bundler is there.
Closes #116

#116: Bundler.with_clean_env was deprecated because the use pattern it was typically being used for wasn't quite right.

---

config/environments/production.rb
config/environments/staging.rb.tt
example.env.tt

This PR adds SMTP configuration to generated apps, so it's ready to go.
Environment variables allow adjustment of the common SMTP params (username, password, host, port), while the domain uses the production or staging hostname used everywhere else throughout the app.
Closes #119

Closes Issue #119: Add SMTP configuration to production. This is inherited by staging

---

config/puma.rb

Fix for #138 
Sorts out the rubocop errors in `puma.rb` that are currently blocking a bunch of PRs from getting merged.

fix rubocop errors in puma.rb

---

config/initializers/content_security_policy.rb
variants/frontend-base/template.rb

This pr contains a fix for an issue in the template where violations of CSP would result in attempts to report the violation in environments such as development and test where reporting isn't configured. [This fix is the one suggested in the comments in the issue where the reporting url is moved to an environment variable.](https://github.com/ackama/rails-template/issues/124)

Made CSP reporting url use an environment variable

---

variants/frontend-base/template.rb

Servers often do not install JS packages from `devDependencies`.
`dotenv-webpack` is required to run `rake assets:precompile` so needs to
be available on servers.
Fixes #115

Make dotenv-webpack available on servers

---

config/application.rb
template.rb
variants/frontend-base/sentry/template.rb
variants/frontend-react/template.rb

[Rails 6.1 changed their requires in templates to use double quotes](https://github.com/rails/rails/pull/38841), so now the generator fails because it can't find `require 'rails/all'`, leading to the require for `http_basic_auth` to be not be added.

fix: support rails 6.1

---

variants/frontend-base/js-lint/template.rb

The CI script already audits Ruby packages with `bundle-audit`. It
should also audit JS packages.
Fixes #168

Run 'yarn audit' as part of generated CI script

---

.github/workflows/ci.yml
template.rb
variants/frontend-typescript/.eslintrc.js
variants/frontend-typescript/app/frontend/components/home/index.tsx
variants/frontend-typescript/app/frontend/components/utils/Form.tsx
variants/frontend-typescript/app/frontend/components/utils/TextInput.tsx
variants/frontend-typescript/app/frontend/components/utils/index.ts
variants/frontend-typescript/template.rb
variants/frontend-typescript/tsconfig.json
variants/frontend-typescript/types.d.ts

Closes #186 
I've made this as technically a `react-typescript` variant, as I need to checkout the setup for foundation to see if it's compatible or if I'd have to setup a pipeline.
Included in this is a small couple of components that I've included for three main reasons:
1. Showing off a possible good way to structure the components (based on structure used for a certain boat related app which I thought was very nice- effectively `components` sets out to mirror `views`), 
2. To provide some examples of how to type React/JSX components,
3. Showing off a couple of the basics of React for things like `useState`, `useCallback`, `props.children`, and conditionally rendering components.
-----
I actually expect CI to fail on this initially - when running locally it would throw an error about …

feat: create typescript variant

---

variants/frontend-base/sentry/template.rb
variants/frontend-typescript/template.rb

v7 is currently throwing errors on webpack 4: https://github.com/mrsteele/dotenv-webpack/issues/369
This is currently breaking CI, i.e #218

fix: pin `dotenv-webpack` to v6

---

variants/frontend-typescript/template.rb

[I messed up the version constraint 😅](https://github.com/ackama/rails-template/pull/219/files#r593978317).

fix(typescript): pull in valid version of `dotenv-webpack` types

---

.auditapprc.json
package.json
variants/frontend-base/js-lint/template.rb

[`audit-app`](https://www.npmjs.com/package/audit-app) is a tool I wrote to make js auditing a bit nicer in a couple of ways, including supporting ignoring vulnerabilities.
[An advisory for `xmldom` was opened 2 days ago](https://www.npmjs.com/advisories/1650) which is pulled in by `lighthouse` via `jsonld` - the version of `jsonld` being used is very low (which in turn is using a very low version of `xmldom`) meaning we're unlikely to see `lighthouse` release a new version that pulls in the patched version of `xmldom` anytime soon.
Since this means all our CIs will be failing, I feel this is the right time to switch to using `audit-app` in our projects. CodeCare is already using it in our auditing tools, and it's been a nice experience so far.
When the vulnerability we're ignoring is no …

feat: use `audit-app` for js auditing

---

variants/frontend-typescript/template.rb
variants/frontend-typescript/types.d.ts

By chance someone added [types to DefinitelyTyped for `@rails/actioncable`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51582), meaning we can remove ours 🎉

fix(typescript): use `@types/rails__actiontable`

---

variants/frontend-typescript/template.rb

I didn't remove this in #218, and now it's causing conflicts.

fix: remove duplicate installing of `@types/actioncable`

---

rubocop.yml.tt

This sprang up from a conversation me & @eoinkelly had when working on a new Rails project - these rules appear like ones we'd actually like to go with the rubocop default, but that were likely disabled back when we had a big shared config file to avoid breaking legacy codebases (the `Rails/` cops) or something that we actually do so rarely we've not really thought about changing the cop (`SpaceAroundEqualsInParameterDefault`).
We're not planning to actively backport these to existing projects.
Happy to discuss if anyone has objections or comments :)

Adjust rubocop config

---

bin/ci-run

The config setup by `@rails/webpacker` and co expect that
`NODE_ENV=test` means you're running tests for JS unit testing, e.g.
with a library like `jest` in a Node process instead of in a real
browser, and so change configuration for tools like babel to target the
current version of node instead of applying all transformations.
Attempting to compile assets with `NODE_ENV=test` will result in errors
because webpack is expecting babel to have transformed new syntax like
the `??` operator for browsers to run the code.
Also see: https://github.com/rails/webpacker/issues/2654

ci: don't set `NODE_ENV` to `test` when precompiling assets

---

.github/workflows/ci.yml

(This is mainly because I want to see if the node version is affecting a local build problem with Babel)

ci: update node

---

Gemfile.tt
config/initializers/sentry.rb
variants/sidekiq/template.rb

Replaces the deprecated sentry-raven gem with sentry-ruby and sentry-rails. Updates initializer. Also adds sentry-sidekiq for sidekiq variant.

Replace sentry-raven with sentry-ruby and variants.

---

config/environments/production.rb
rubocop.yml.tt

* It reduces the volume of output from running the template.
* Our track record is that we accept new cops a lot more often than we
reject them so enabling new cops by default seems sensible.
* Fix minor rubocop failure caused by enabling new cops

Enable new rubocop cops by default

---

rubocop.yml.tt

The ExampleLength is causing PR #257 to fail. I don't think long examples are a problem. In fact they are something to encourage if the test setup is slow e.g. feature specs. I have bumped the limit to 30 to reflect this.
`RSpec/FactoryBot/SyntaxMethods` fails if we use `FactoryBot.create` instead of `create` in tests which seems a bit too magical for it's own good and we have rough consensus about that on Slack.

Tweak rubocop settings to match Ackama preferences

---

.github/workflows/ci.yml
config/application.rb
config/template.rb
template-test/ci-run.sh

Two major fixes:
1) Move the insertion of `require_relative '../app/middleware/http_basic_auth'` to after `require_relative 'boot'` to ensure that the HttpBasicAuth constants get initialized.
2) Skip writing to `storage.yml` if that file doesn't exist (which it doesn't when `--skip-active-storage` is set)
Also adds a new variable `SKIPS` in the CI run that allows us to have a run that can include skip flags. Have moved the "always skip javascript" line that was added for Rails 7 to this section so that it's always in one place.
Closes #107 and #108

Fix: using --skip options fails to generate apps

---

README.md
variants/frontend-react/.eslintrc.js
variants/frontend-react/app/frontend/components/HelloWorld.jsx
variants/frontend-react/app/frontend/test/components/HelloWorld.spec.jsx
variants/frontend-react/app/frontend/test/setupExpectEachTestHasAssertions.js
variants/frontend-react/jest.config.js
variants/frontend-react/template.rb

This adds [react-testing-library](https://testing-library.com/docs/react-testing-library/intro/) to the react variant, along with a sample test & linting configuration.
Closes #216
Closes #208

feat: add react testing library to react variant

---

spec/rails_helper.rb

Apparently this sort is now redundant - Rubocop was the reason why this was added in the first place, but just going to go with it 🤷

fix: remove redundant sort

---

simplecov
spec/spec_helper.rb
template.rb

After this change we no longer create a `.simplecov` file. I think that
keeping the config in `spec/spec_helper.rb` is less surprising.
This also resolves an issue where the SimpleCov setup in `.simplecov`
was different to that in `spec/spec_helper.rb`.

Load SimpleCov config from just one place: spec/spec_helper.rb

---

.github/workflows/codeql-analysis.yml

This updates the CodeQL workflow using the standard GH template - the main changes are that we've now using the new major versions (which we need to switch to before the end of the year) and enables the `typescript` language (as I learnt the other day while it's not listed as a supported language in the template comments & `javascript` will give results on TS files, it is apparently different and so the best setup is to have both `javascript` & `typescript` listed as languages 🤷).

ci: update codeql workflow

---

rubocop.yml.tt

It's automatically inferred from `.ruby-version` (if it exists) and `Gemfile.lock` (if it has the ruby version), which both exist in this template, meaning explicitly defining it just adds another change that needs to be made when upgrading apps to newer versions of Ruby.
(the purpose of this config property is in case you target a range of Ruby versions and want Rubocop to only use syntax from the lowest version you support to help ensure compatibility - useful if you're a library, but not if you're an application)
https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version

fix: remove `TargetRubyVersion` from rubocop config

---

variants/sidekiq/config/initializers/sidekiq.rb.tt

This error will be a default in Sidekiq 7+ so we are explicitly raising
the error now to make upgrading Sidekiq easier. Details in
https://github.com/mperham/sidekiq/wiki/Best-Practices.
Closes #298

Make Sidekiq raise an error if job args do not serialize safely to JSON

---

config/environments/production.rb

I missed this when reviewing #296 - I'm also getting an error about the `redis` gem not being in the Gemfile, but not sure if we want to be including that by default since we can't make it conditional like we can with actually trying to use Redis; the error message is helpful enough that I think we don't need to do anything if we're happy with the gem needing to be added manually.

fix: make `RAILS_CACHE_REDIS_URL` env properly optional

---

spec/requests/http_basic_auth_middleware_spec.rb

Looks like the latest version of `rubocop-rails` is now picking this up.

test: use `have_http_status` matcher in basic auth specs

---

variants/pundit/template.rb

Raise an ActiveRecord::RecordNotFound if the user is not authorised so
that the user sees the same error message for unauthorised access and
missing resource. This prevents the user from enumerating which
resources exist in the database and addresses an issue which was raised
in a pen test.
I have left the original code in the method (commented out) so that users have access to a good implementation of the user-friendly version. I'm not :100: this is the right move so feedback particularly welcome on that.

Raise an ActiveRecord::RecordNotFound if the user is not authorised

---

README.md.tt

The account manager is a really useful contact to have in the project README. Frequently, the account manager will have access to more records and context around the intended and contracted feature set of the application, especially for older phases of work.

Add Account Manager role to README

---

Dockerfile
README.md.tt
config/initializers/content_security_policy.rb
variants/devise/spec/system/user_sign_in_feature_spec.rb
variants/devise/spec/system/user_sign_up_feature_spec.rb
variants/frontend-base/sentry/template.rb
variants/performance/spec/performance_helper.rb

so maybe its too early to add a new linter (#312) but it's not to early to fix some typos

Fix some typos found by prematurely adding spellr

---

variants/frontend-bootstrap/template.rb

Without `--exact`, yarn will add `^5.1.3` to `yarn.lock` which allows `5.2.0`,
the version which is currently broken for us

Force yarn to use the exact version of bootstrap we have specified

---

config.ru.rb

Before this change, we use
[rack-canonical-host](https://github.com/tylerhunt/rack-canonical-host)
with the `HOSTNAME` env var. This can clash with an env var already
defined by the deployed environment e.g. https://render.com
Render.com sets `HOSTNAME` but doesn't set
it to a fully qualified domain e.g. it sets it to something like
`HOSTNAME=srv-cbm836fho1kta1m6cu6g-5fb64bb76c-qvsd5`. This means our
setup in `config.ru` breaks out of the box because we try to HTTP 301 to
`https://srv-cbm836fho1kta1m6cu6g-5fb64bb76c-qvsd5/`. This also doesn't
generate any logging output so is quite confusing to debug.
This change renames the env var we use for `rack-canonical-host` to
`CANONICAL_HOSTNAME` to avoid this clash.
Closes #328

Rename canonical hostname env var to avoid pre-defined env vars

---

example.env.tt

Rails will not boot in production env without these env vars. It is
sometimes convenient to boot the app in production env locally for
debugging (we already document this in the README).
Uncommenting these lines is safe to do and is one less papercut for
doing this.
Closes #327

Uncomment SMTP_* env vars required to run app in production env

---

config/environments/production.rb

and make the comment clearer
this logic seems to have been inverted in
a2ac42b86906eba4036ceed6a527a3effc8ece34
i added 'true' as the default for the fetch argument for clarity of intent only, if this env variable isn't present then treat it as true

Fix the logic for force_ssl to match the comment

---

variants/frontend-react/app/frontend/test/setupExpectEachTestHasAssertions.js
variants/frontend-typescript/app/frontend/test/setupExpectEachTestHasAssertions.ts

I landed a huge improvement to how we check for `expect` calls over in `eslint-plugin-jest`, which means `no-standalone-expect` is now _correctly_ flagging this call as a standalone `expect` since it's not in a describe.
Our usage here is valid, it's not just supported by `no-standalone-expect` as it's considered an advanced usage and it's a one-liner to disable like this (vs having people stumble into finding it is considered valid without knowing how it's meant to be used)

chore: disable jest linting rule

---

variants/devise/template.rb

Closes #338
We were installing devise-locakable but not configuring it. This change
configures lockable with what we believe to be sensible defaults.

Configure devise-lockable

---

template.rb

[I've adjusted `shakapacker`](https://github.com/shakacode/shakapacker/pull/170) to determine the version being used based on the lockfile so we no longer need to pin it in `package.json`, making it easier to update if needed.

feat: unpin shakapacker dependency

---

package.json
yarn.lock

This resolves all known security vulnerabilities in our `yarn.lock`, which is required for #351

feat: upgrade stylelint & co

---

variants/frontend-react-typescript/template.rb
variants/frontend-react/template.rb

* Allow pinning of the major version of `jest` package to ensure that it
installs a version which has an available `ts-jest` package.
This fixes an issue where CI cannot currently build the react-ts variant.

Fix latest 'jest' and 'ts-jest' versions not being compatible

---

.github/workflows/ci.yml
ackama_rails_template.config.yml
ci/configs/basic.yml
ci/configs/bootstrap-typescript.yml
ci/configs/bootstrap.yml
ci/configs/deploy_with_ackama_ec2_capistrano.yml
ci/configs/deploy_with_capistrano.yml
ci/configs/react-typescript.yml
ci/configs/react.yml
ci/configs/sidekiq.yml
template.rb
variants/deploy_with_ackama_ec2_capistrano/aws_ec2_environment.yml
variants/deploy_with_ackama_ec2_capistrano/template.rb

Add a Capistrano variant which specifically targets Ackama's preferences around deploying Rails on EC2.
This was created by extracting the setup we used on a recent client project.

Ackama specific capistrano variant

---

README.md.tt
rubocop.yml.tt
template.rb
variants/code-annotation/template.rb
variants/github_actions_ci/workflows/ci.yml

I have worked on a number of projects which included these gems and the teams (including myself) have enjoyed having the annotations. The model annotations are particularly handy if you are unfamililar with the codebase.
This change:
* Install and run `chusaku` to annotate each controller action with a comment detailing the route which targets that action.
* Install and run `annotate` to annotate models, fixtures with the schema details of the model. `annotate` runs automatically after migrations.
* Setup CI to check that both `chusaku` and `annotate` annotations are up to date.
Closes #366

Set up Rails route and model code annotations

---

ackama_rails_template.config.yml
template.rb

It's easy to think that if you're wanting to use our Ackama cap setup you should enable both flags, but that'll result in a weird smashup between two independent variants.
While we could try and handle this with documentation, I think it's better UX if we only respect the "most specific" cap variant that is enabled.

fix: only apply one capistrano variant regardless of what configs are set

---

variants/frontend-react/template.rb

`ts-jest` has released v29, so hopefully this should be fine.

feat: switch to Jest v29

---

variants/devise/template.rb

This change modifies `lock_strategy` to `unlock_strategy`, since setting the lock strategy to `:email` instead of failed_attempts is not rejected, but causes the check in https://github.com/heartcombo/devise/blob/6d32d2447cc0f3739d9732246b5a5bde98d9e032/lib/devise/models/lockable.rb#L103 to return false, skipping any enforcement of account locking.

Use correct configuration key so that the lockable strategy is activated

---

variants/backend-base/config/application.rb

Set `X-Frame-Options`  to the more secure `deny` value. Allowing our site to be embedded in an iframe is not something we want to support by default.
Closes #386

Prevent embedding the app as iframe by default

---

variants/deploy_with_ackama_ec2_capistrano/template.rb
variants/deploy_with_capistrano/template.rb

Me and @eoinkelly spoke about this a few months back when we inherited a project that has a rather bloated git repo meaning that clones could take a good couple of minutes; I've since been trying this on another project without issue, and while we're probably talking saving a few seconds on average, it's still nice to speed up deployments.

feat: use shallow clone when deploying with capistrano

---

template.rb

This helps ensure services like Heroku don't automatically install `yarn` v2 due to a lack of constraint - we don't use v2 (aka yarn berry) because it is effectively a whole new CLI which was never compatible with Rails, and while Rails is moving on from being involved in JS our existing apps are all using v1 and we prefer `npm` anyway so if things get more relaxed in future that'd probably be our path anyway.

fix: lock `yarn` to v1 via `engines`

---

.github/workflows/ci.yml
variants/github_actions_ci/workflows/ci.yml.tt
variants/github_actions_ci/workflows/deploy_to_ec2.yml
variants/github_actions_ci/workflows/deploy_to_heroku.yml

This hardens our CI permissions to make it a bit harder to exploit, should something nasty manage to slip by - currently the most likely way this could happen is through external dependencies i.e. if someone crafts a package that is designed to act like a useful package until it detects it's in a GHA CI environment, after which it tries any number of bad things (which can include silently creating a new branch and committing a new GHA workflow and .... I'm going to leave it there), or if one of the GitHub Actions we're using gets compromised in a similar fashion; this also puts us in a good position if/when we have tighter permissions around who can do what on repos.
I have tested this on a project that is being moved from Heroku to AWS, so I'm pretty sure these permission changes for …

ci: harden workflow permissions

---

variants/frontend-base/js-lint/template.rb

"defaults" already excludes IE stuff now - see https://browsersl.ist/#q=defaults%2C+not+IE+11%2C+not+IE_Mob+11

Modernised browserslist list of browsers

---

variants/deploy_with_ackama_ec2_capistrano/template.rb

For me having `rbenv_path` set with our setup causes `capistrano-rbenv` to error saying it can't find the version of Ruby, which I assume is that it mucks with the fact we're using fullstaq (because it's looking under the `.rbenv` path).
We also need to set the `deploy_to` path since the default is `/var/www` which is not our standard path, and might as well set `user` too.

fix: ensure `user` and `deploy_to` are set, and `rbenv_path` is not set, in Ackama capistrano variant

---

variants/backend-base/bin/setup

But also runs migrations if necessary, and creates the db if necessary
This reduces unecessary changes to the schema file, and is a much more straightforward way to build a db structure

Use db:prepare which schema:loads rather than migrating from scratch

---

variants/backend-base/app/views/layouts/application.html.erb.tt
variants/backend-base/config/initializers/version.rb

Replace shelling out to git (which only works in some environments) with the OkComputer check which supports checking more environments:
* The `REVISION` file created by Capistrano
* The `ENV["SHA"]` variable set by platforms like Heroku
This change also removes `Rails.application.config.version_time` because there is no way to get this information in a cross-platform way.
Closes #382

Use OkComputer to find git SHA of current deployment

---

Gemfile.lock
variants/backend-base/rubocop.yml.tt

We use Capybara all the time so this seems sensible. It also silences a warning from rubocop when you run it in the generated apps:
```
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-capybara
You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```

Enable rubocop-capybara which is included in rubocop-rspec gem

---

variants/frontend-bootstrap/app/frontend/stylesheets/customized_bootstrap.scss

v5.3.0 introduced this, or more specifically this has variables in it that are used by other parts of bootstrap so we have to import it

fix: import required bootstrap stylesheet

---

variants/frontend-base/js-lint/template.rb

v3 was released a couple of days ago, and among other things drops support for its sync API which means ESLint can't use it anymore - I expect the ecosystem to react, but as of right now we can't "just use v3".

fix: lock `prettier` to v2

---

.github/workflows/ci.yml

Makes it a bit less confusing when you're looking at error logs in CI that have the path i.e. `No such file or directory @ rb_sysopen - /home/runner/work/rails-template/rails-template/tmp/builds/ackama_ec2_capistranodemo/config/webpacker.yml (Errno::ENOENT)` since to me `ackama_ec2_capistranodemo` smells like a `path.join` type bug

ci: make app name a bit clearner

---

variants/frontend-base-typescript/template.rb
variants/frontend-base/js-lint/template.rb
variants/frontend-bootstrap-typescript/template.rb

I had assumed that the new major of `eslint-plugin-prettier` would be compatible with both v2 and v3, but I was wrong - of course it got released _after_ I opened #442...
Similarly `@typescript-eslint` released v6 this week - for now I'm just locking us to v5 to move towards a green CI but expect to do the minor work required to support v6 later this month.

fix: use latest prettier and lock `@typescipt-eslint` to v5

---

variants/frontend-base/template.rb

This was the only instance I found of an image path being generated by the template

Make image page compatible with shakapacker v7

---

template.rb
variants/backend-base/bin/ci-run
variants/backend-base/config/template.rb
variants/backend-base/docker-compose.yml
variants/frontend-base-typescript/types.d.ts
variants/frontend-base/config/webpack/webpack.config.js
variants/frontend-base/template.rb
variants/frontend-react-typescript/types.d.ts
variants/performance/spec/performance_helper.rb

See https://github.com/shakacode/shakapacker/blob/master/docs/v7_upgrade.md - I havn't yet confirmed if we need to make any changes for the "Stop stripping top-level dirs for static assets" section.

fix: support `shakapacker` v7

---

.rubocop.yml
variants/backend-base/rubocop.yml.tt

This is the sister rule to `Layout/FirstHashElementIndentation` which we adjusted in #433 - I hadn't realised it was a thing, but I assume everyone agrees it makes sense to have them .. er.. consistent with each other 😅

fix: change `Layout/FirstArrayElementIndentation` to be `consistent`

---

.github/workflows/ci.yml
variants/accessibility/Gemfile.rb
variants/backend-base/Gemfile.tt

Rails 7.0 supports Ruby 3.2.x (latest stable Ruby) so it makes sense that we should run our CI against it rather than 3.0.x
Closes #444
Closes #453

Run CI against latest stable Ruby

---

variants/frontend-bootstrap-typescript/template.rb

The base typescript variant already installs it, so we don't have to as part of this variant.

refactor: don't install `@typescript-eslint` again in bootstrap typescript variant

---

variants/github_actions_ci/workflows/ci.yml.tt

Technically API-only apps won't need this but we pretty much never do those and this shouldn't error so at worse it'll just add a couple of seconds to CI.
Resolves #456

fix: explicitly setup `node` and run `yarn install` before running specs

---

README.md

I'm happy if someone wants to improve how this is explained around the rest of the doc so it's less of a "short random sentence", but at least now it is documented.

docs: mention that postgres is required to run the generator

---

variants/backend-base/lib/tasks/assets.rake

This was removed in Shakapacker v7 though our CI doesn't fail because we're already installing it before every command - but that does not happen for deployments.

fix: ensure that frontend assets are installed before (pre)compiling

---

variants/github_actions_ci/workflows/ci.yml.tt

[Thor runs ERB with `trim_mode` set to `-`](https://github.com/rails/thor/blob/main/lib/thor/actions/file_manipulation.rb#L126C68-L126C82) which means that `<%-` and `-%>` are required to do whitespace trimming - this is different from Rails where whitespace trimming is automatically applied:
> When on a line that only contains whitespaces except for the tag, <% %> suppresses leading and trailing whitespace, including the trailing newline. <% %> and <%- -%> are the same.
<details>
<summary>comparisons of the difference when running through Thor given a snippet from our GitHub Actions workflow template</summary>
```
❯ cat -e my_file.yml
$
env:$
RAILS_ENV: test$
DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres$
RAILS_SECRET_KEY_BASE: …
```

fix: don't include trailing whitespace or newlines in GitHub Actions workflow

---

.github/workflows/ci.yml

I don't think there's any advantage to running `rubocop` _before_ we do every test in the matrix - this way (in theory) our matrix jobs are a little faster and they'll still run even if you have `rubocop` errors.

ci: run `rubocop` in its own job

---

variants/frontend-stimulus-typescript/jest.config.ts
variants/frontend-stimulus-typescript/template.rb
variants/frontend-stimulus/app/frontend/test/setupJestDomMatchers.js
variants/frontend-stimulus/jest.config.js

I'm on the fence about switching to have just a single `setup.js|ts` file as then we might have to do more logic on adding to that without conflicting, but it might be fine as we're not really doing that much and I don't expect we'll have more to add in the future...
Still we can make that switch later - for now I just want to get CI back in the green.

fix: import `@testing-library/jest-dom` matchers in their own setup script

---

variants/backend-base/lib/template.rb

fix: actually copy `assets.rake` tasks

---

variants/frontend-base/template.rb

When autocompilation happens, our lighthouse performance specs fail intermittently.

bug: Tell Shakapacker not to auto-compile in test env

---

variants/frontend-base-typescript/template.rb

Our eslint config now requires `@typescript-eslint` v6
Resolves #481

fix: use latest version of `@typescript-eslint`

---

.github/workflows/ci.yml
ci/bin/build-and-test
template.rb

This is what we recommend since our template handles setting up JavaScript related bundling, but we don't enforce it nor do we do it by default in `ci/bin/build-and-test` meaning running locally Rails can try to install importmaps and other stuff.
I think at the least we should make `build-and-test` include `--skip-javascript` as the default for `SKIPS`, but we can also actually enforce that its provided; if we don't want to do that, then we should ensure that the template is tested _without_ the flag instead.

fix: ensure that `--skip-javascript` is always enabled

---

variants/backend-base/app/views/layouts/application.html.erb.tt
variants/backend-base/config/initializers/version.rb
variants/deploy_with_ackama_ec2_capistrano/template.rb
variants/deploy_with_capistrano/template.rb

This is something I explored due to a requirement for a particular application to have a version identifier in its admin panel even though we do continuous deployments; for that app there'll be additional work to display `version_time` on the actual page, but I think the underlying feature is useful since `version` (aka the commit sha) is only meaningful if you either note the version over time (in which case you can know if it changes) or if you have access to the source code.
I'm opening this as a draft for now because this is literally the first time I'm sharing the implementation so maybe its completely broken or concerning, but hopefully not 🙂
I have confirmed this works using an example site:

feat: support setting and displaying the revision time for capistrano-based deployments

---

variants/frontend-base/template.rb

Enable Rails-Turbo

---

variants/github_actions_ci/workflows/deploy_to_ec2.yml

This removes warnings about old versions of NodeJS when running the action.
Closes #486

Upgrade action which configures AWS credentials to latest version

---

variants/backend-base/config/application.rb

Gzipping responses trades some server and browser CPU for less data over the network. This is particularly helpful for browsers on unstable or slow Internet connections.
Closes #418

Gzip Rails responses by default

---

variants/backend-base/config/initializers/version.rb

`Time.utc` expects to be provided year, month, day, etc as arguments - instead we should be calling `utc` on the constructed time.

fix: call utc on time correctly

---

variants/backend-base/config/initializers/version.rb

`String#to_i` works by returning all the digits in a string up to the first non-digit that isn't `_` (they're treated as separators) or the end of the string - if no digits are found then zero is returned.
One of the feedback items on  #461 was that when we can't determine the revision time we should explicitly return `nil` instead of a `Time`; but the above logic of `String#to_i` means we can end up returning the start of the epoch which goes against that.
This changes our logic so that we explicitly return `nil` if we end up getting a zero, ensuring our "Unknown time" logic will be triggered.

fix: return `nil` if revision time ends up being zero

---

variants/backend-base/.erb-lint.yml

This aligns with what Prettier enforces for normal HTML files and what JSX requires; while there is a very small cost in bytes it doesn't outweigh the benefit in being consistent across our stacks and code.
Resolves #509

refactor: always expect self closing tags for void elements in ERB

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
ackama_rails_template.config.yml
ci/configs/all-typescript.yml
ci/configs/all.yml
ci/configs/basic-typescript.yml
ci/configs/basic.yml
ci/configs/bootstrap-typescript.yml
ci/configs/bootstrap.yml
ci/configs/deploy_with_ackama_ec2_capistrano.yml
ci/configs/deploy_with_capistrano.yml
ci/configs/devise.yml
ci/configs/github_actions.yml
ci/configs/react-typescript.yml
ci/configs/react.yml
ci/configs/sidekiq.yml
package.json
template.rb
variants/backend-base/config/app.yml
variants/backend-base/config/pre_commit.yml
variants/backend-base/config/secrets.yml
variants/backend-base/docker-compose.yml
variants/backend-base/overcommit.yml
variants/frontend-base/js-lint/fixes.rb
variants/frontend-base/js-lint/template.rb
variants/frontend-base/sass-lint.yml
variants/github_actions_ci/workflows/deploy_to_ec2.yml
variants/github_actions_ci/workflows/deploy_to_heroku.yml

We originally limited the files we applied `prettier` to a subset (which I think is really just "not yaml"?) when we first started using it, but I think nowdays we're all very comfortable with it and we don't have anything else linting our YAML so lets starting doing that

feat: apply `prettier` to all supported file types

---

variants/github_actions_ci/workflows/ci.yml.tt
variants/github_actions_ci/workflows/deploy_to_ec2.yml
variants/github_actions_ci/workflows/deploy_to_heroku.yml

[Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) have a number of advantages both in terms of security and UX.
Notably we are able to see a list of deployments to environments with a direct link to the environment URL if present:
This is also accessible via API and there are dedicated webhook events for new deployments which are useful for internal automation; deployments to environments also can be restricted to specific branches and can have their own secrets and variables allowing us in future to further DRY up our workflows (I've not done that here because we're still in the process of just switching our existing workflows to using environments, and I don't want to do too much too fast).
Environments are …

ci: use environments when deploying

---

variants/github_actions_ci/workflows/ci.yml.tt

This hasn't caused problems because we don't have multiple workflows in our standard Rails setup, but we hit it on other stacks where we do and there's no downside so might as well do this here as best practice

ci: include workflow in concurrency group

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
variants/github_actions_ci/workflows/ci.yml.tt

In my mind there's a number of advantages to this:
* you can easily see all the permissions a job requires
* the block always exists making it easier to pick up on when you need to add new permissions
* because of this I've also put the `permissions` property as the first one in every job for consistency
* we're leading by example, instead of doing something we're telling people not to do (using a global permission)
Note that our reusable workflows do still have a workflow-level `permissions` property - I've kept this because reusable workflows can only _narrow_ permissions meaning the caller job should still always have a `permissions` block, and so in my mind for reusable workflows `permissions` is more "here's what you need to copy into the caller job" which would be more work if we …

ci: explicitly define permissions for each job and as the first property in each job

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

This isn't super important since this is an open-source repo, but it's useful in #466 to avoid rate limiting and so cherry-picking lets me reduce that PR a little

ci: cancel in-progress jobs automatically

---

variants/backend-base/bin/ci-run
variants/github_actions_ci/workflows/ci.yml.tt

These are the default [since v4.0.0](https://github.com/presidentbeef/brakeman/blob/main/CHANGES.md#400---2017-09-25).
The actual motivator for this is that it brings the line under 80 characters so Prettier is happier, but also really we should be using `config/brakeman.yml` for these settings to ensure all brakeman calls are consistent by default (I've not added that though because I have not seen evidence that brakeman is in the habit of changing its defaults often, so I don't think we need to worry)

fix: omit default brakeman flags

---

variants/devise/template.rb

This improves the default nav we generate by using bootstrap classes which in addition to just making it look nicer will hopefully be slightly more useful by having a working nav implemented since we expect to be using bootstrap as our standard for projects that require such styled frontends.
This degrades gracefully when bootstrap is not present too:
I initially considered making this based on if the bootstrap variant was enabled or adding a comment about it, but ultimately I don't think it'll be that confusing to have these css classes if bootstrap isn't being used.

feat: improve example nav for devise

---

variants/devise/spec/system/user_reset_password_feature_spec.rb
variants/devise/spec/system/user_sign_in_feature_spec.rb
variants/devise/spec/system/user_sign_up_feature_spec.rb

https://github.com/rubocop/rubocop-capybara/pull/76 changed the default to enforce using the more generic `click_link_or_button` and `click_on` because
> These methods offer a weaker coupling between the test and HTML, allowing for a more faithful reflection of how the user behaves.
Which is very fair imo and inline with other testing frameworks like `testing-library`.

fix: use `click_on` rather than `click_link` and `click_button`

---

variants/backend-base/spec/rails_helper.rb

This matches more closely what gets generated by Rails 7.1, which can help reduce the diff when e.g. install ActionText - I think the biggest practical gain is replacing the `relishapp` link since that app is now down (probably for good 😞), along with a couple of shorteners.

refactor: update `rails_helper` based on latest Rails

---

variants/backend-base/config/puma.rb

This pull request updates the Puma configuration to set a worker timeout of 3600 seconds in the development environment. This ensures that the worker isn't killed by Puma when suspended by a debugger.
This steals an idea I saw in https://github.com/rails/rails/pull/50669/files.

Update Puma configuration to set worker timeout in development environment

---

.github/workflows/ci.yml
variants/github_actions_ci/template.rb

While rebasing #466 after #516 was landed I learned that I had actually mucked up my erb for the GitHub Actions workflow - this was only picked up because it was invalid YAML so Prettier errored.
To help avoid mistakes in future, this introduces running [`actionlint`](https://github.com/rhysd/actionlint) as part of our _template_ CI.
Since doing so means that `bin/ci-run` now includes a tool that isn't in our CI workflow, this PR can also be seen as the initial nudge towards a possible future with a very different approach to `bin/ci-run` (including not having it at all) that I've been wanting to bring up for discussion for a bit.

feat: run `actionlint` for GitHub Actions variant

---

variants/accessibility/spec/system/home_feature_spec.rb
variants/audit-logging/template.rb
variants/backend-base/config/application.rb
variants/backend-base/config/environments/staging.rb.tt
variants/backend-base/config/template.rb
variants/frontend-base/template.rb
variants/frontend-bootstrap/template.rb
variants/github_actions_ci/workflows/ci.yml.tt
variants/pundit/template.rb

These are some changes that are typically autofixed during generation - while there's no major drawback, I think it's nice to aim for our written template code to match our preferred formatting out of the gate.
MVP goes to `home_feature_spec.rb` whose lack of a newline upset not one but _three_ cops:
```
spec/system/home_feature_spec.rb:13:1: C: [Correctable] Layout/IndentationConsistency: Inconsistent indentation detected. (https://rubystyle.guide#spaces-indentation, https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#follow-the-coding-conventions)
it_behaves_like "an accessible page"end
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/system/home_feature_spec.rb:13:37: C: [Correctable] Layout/BlockEndNewline: Expression at 13, 37 should be on its own line.
it_behaves_like "an …
```

refactor: apply some formatting fixes

---

template.rb
variants/frontend-base-typescript/template.rb
variants/frontend-base/js-lint/template.rb
variants/frontend-react/template.rb
variants/frontend-stimulus-typescript/template.rb
variants/frontend-stimulus/template.rb

I'm aware of how much conflict this will create with #466 but oh well 🤷

refactor: create a dedicated method for updating `package.json`

---

variants/frontend-base/template.rb

[`react-rails` now supports other package managers](https://github.com/reactjs/react-rails/pull/1306) using `package_json`, meaning it now defaults to `npm` if a package manager is not explicitly set in `package.json`, causing a stray `package-lock.json` to be created.
I've specified an exact version because currently `corepack` requires that ([ranges are not yet supported](https://github.com/nodejs/corepack/issues/95)) but we're not actually expecting anyone to be using `corepack` and we're definitely not using it in production (not explicitly at least...) so in theory this shouldn't cause problems and it means `package.json` conforms to the JSON schema - it'll also help to flush out any potential problems early before(/if) `corepack` becomes more mainstream.

fix: explicitly set our preferred package manager for js dependencies

---

variants/frontend-base/.stylelintrc.js

These mirror options we've got enabled in other linting like Rubocop, ESLint, and TypeScript

feat: report needless and invalid stylelint disables, and require descriptions

---

template.rb
variants/backend-base/app/template.rb
variants/backend-base/config/application.rb
variants/backend-base/config/environments/development.rb
variants/backend-base/config/environments/production.rb
variants/backend-base/config/environments/test.rb
variants/backend-base/config/template.rb
variants/deploy_with_ackama_ec2_capistrano/template.rb
variants/deploy_with_capistrano/template.rb
variants/devise/template.rb
variants/frontend-base-typescript/template.rb
variants/frontend-base/sentry/template.rb
variants/frontend-base/template.rb
variants/frontend-bootstrap/template.rb
variants/frontend-react-typescript/template.rb
variants/frontend-react/template.rb
variants/sidekiq/template.rb

So it turns out that `gsub_file` does not actually check if it matched anything and so we have a few misc. changes silently not being applied due to changes in Rails 7.1.
This addresses that by switching us to use `gsub_file!` which reads the file into memory before it's gsub'd and then compares the results to make sure it actually changed.
I've opened https://github.com/rails/thor/issues/874 to add this to Thor itself

fix: use a safer `gsub_file` and update/remove file gsubs that were no longer doing anything

---

variants/backend-base/bin/setup

I don't use overcommit, i use hooks stored in dotfiles
overcommit helpfully installs its hooks in `[the project dir]/[a literal tilde]/.dotfiles/hooks` which is not what anyone wants.
this means i can turn this off when running the rails new everything command with rails template (usually i just won't use bin/setup directly)

Optionally skip overcommit

---

variants/frontend-stimulus-typescript/jest.config.ts
variants/frontend-stimulus-typescript/template.rb

TIL `jest` re-exports this type from `@jest/types`, which means we can drop it as a direct dependency

feat: import Jest config type from `jest` rather than `@jest/types`

---

variants/frontend-base-typescript/template.rb
variants/frontend-base/js-lint/template.rb

ESLint v9 has been released which drops support for the old config structure in favor of "flat config", which we're not yet ready to switch to

fix: lock ESLint to v8

---

variants/frontend-base-typescript/template.rb
variants/frontend-bootstrap-typescript/template.rb
variants/frontend-bootstrap/template.rb

Yarn already installs packages as part of adding them, so there's no need to immediately run `yarn install` afterwards

perf: remove unneeded `yarn install` calls

---

variants/backend-base/spec/rails_helper.rb
variants/devise/spec/system/user_sign_in_feature_spec.rb

The issue seems to be that within the next 2 weeks is a dst change so we aren't 14 days away, we're 14 days +- 1 hour away (i can't be bothered figuring out which direction currently), which when rounded to days at utc was sometimes out by a day
by keeping the comparison to datetimes rather than a raw number of days or seconds, then ruby/rails can keep track of the impact of dst and things will just work
i've included the time helpers setup in base rather than in just the devise variant because i think it's broadly useful and its provided by rails we might as well make it accessible to rspec

Fix DST causing sign in spec to fail

---

variants/pundit/template.rb

[Pundit have recently changed](https://github.com/varvet/pundit/pull/776) to using `NoMethodError`, which breaks our spec - the main benefit of this change is that the new error extends from `StandardError` so in theory is easier to catch; however, it seems the community is divided as aside from the different superclass the existing error is more accurate since `NoMethodError` is meant to be thrown when the class does not `respond_to?` the method in question and that is not true.
I personally would like to keep using `NotImplementedError` though I'm happy to change if someone does prove a real-world situation where it's more burdson to catch (or that our error monitoring won't catch it), but I feel that should be a separate conversation - so this PR is changing it back to maintain our …

fix: check for `NoMethodError` instead of `NotImplementedError`

---

variants/frontend-base/template.rb

The most notable feature change in v8 is that Shakapacker is now JS package manager agnostic by default, using the [`packageManager`](https://nodejs.org/api/packages.html#packagemanager) property to determine which package manager to use (otherwise defaulting to `npm`, like Node itself).
A side-effect of this means that `shakapacker:install` now _merges_ with existing `package.json`s rather than always overwriting it (that way you can set `packageManager` before running the installer); this means we could potentially refactor some of our `package.json` related code to reduce duplication but it'll still all work as-is so I've left that for a potential follow-up PR.
There are other breaking changes which are detailed [in the upgrade …

fix: support `shakapacker` v8

---

.github/workflows/ci.yml
variants/github_actions_ci/workflows/ci.yml.tt

v4 uses a later version of Node but does not have any other notable breaking changes

ci: upgrade `actions/setup-node` to v4

---

variants/frontend-react/template.rb

[v16.0.0 now requires `@testing-library/dom` as a peer dependency](https://github.com/testing-library/react-testing-library/releases/tag/v16.0.0), which means we need to explicitly include it as a direct dependency at least while we're using Yarn which doesn't automatically install peer dependencies.
We already add `@testing-library/dom` as a direct dependency in the Stimulus variant which is always installed, so we just need to stop removing it in the React variant.

fix: retain `@testing-library/dom` as a direct dependency even when `@testing-library/react` is used

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile.lock
README.md
ci/bin/build-and-test
target_versions.yml
template.rb
variants/backend-base/Gemfile.tt
variants/devise/template.rb
variants/frontend-base-typescript/template.rb

Create a central place to manage which versions of Ruby and Rails this template supports.
This change introduces a new configuration file called `target_verions.yml`. This file holds data about which versions of Ruby and Rails are currently compatible with the template. 
The data is used in multiple contexts:
1. The template itself uses it to verify that the version of Rails being used to run the template is compatible
2. CI uses it to choose a compatible version of Rails to install
3. Rubocop configuration for this repo uses it to ensure that Rubocop checks which run against this repo will be compatible with all versions of Ruby and Rails which the template supports. The Rubocop configuration in the generated apps does not need this information because it can infer it from the specific …

Centralise and improve Rails version handling

---

.github/workflows/ci.yml
ci/bin/create-fake-js-package-managers
template.rb
variants/accessibility/spec/rails_helper.rb
variants/backend-base/bin/setup.tt
variants/backend-base/lib/tasks/assets.rake.tt
variants/backend-base/lib/template.rb
variants/backend-base/spec/rails_helper.rb
variants/frontend-base-typescript/template.rb
variants/frontend-base/babel.config.js
variants/frontend-base/js-lint/template.rb
variants/frontend-base/template.rb
variants/frontend-react-typescript/template.rb
variants/frontend-react/template.rb
variants/frontend-stimulus-typescript/template.rb
variants/frontend-stimulus/template.rb
variants/github_actions_ci/workflows/ci.yml.tt

This allows us to support all of the major javascript package managers by relying on the [`package_json`](https://github.com/shakacode/package_json) gem to handle running and generating commands for a particular package manager.
Currently I'm making our template actually agnostic and have setup to test that is the case by running against the major package managers + Yarn PnP, though I expect after landing this we'll decide on a single package manager to use going forward and remove code that is needed for the other package managers.

feat: switch to using `package_json` for interacting with `package.json`

---

variants/github_actions_ci/workflows/ci.yml.tt

Without this, `chusaku` will just print a message saying that it has run but with no indication of what was actually missing an annotation, which can be annoying when you swear you did run it - even though the fix is to run `bundle exec chusaku` locally which doesn't require knowing what needs annotating, logs are free so we might as well be verbose here

ci: make `chusaku` output verbose

---

template.rb

It seems that something had changed in Ruby 3.3.6 that means for some reason unless we maintain the old env, the use of `bundler/inline` causes Bundler to error about gems not being present when we (very) later call `run "bundle install"`.
I have no idea what has actually changed, as while I confirmed everything is passing if we switch to Ruby 3.3.5, I couldn't get a smaller reproducible example that showed the exact same behaviour 🤷

fix: ensure env doesn't get clobbered when installing `package_json`

---

variants/github_actions_ci/workflows/ci.yml.tt

v3 has been deprecated as v4 moves to an immutable-based design which has some performance benefits, among other things; that change doesn't impact how we're using artifacts, but that's all the more reason to upgrade.
See [the migration notes for more information](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) for more about what's changed.

fix: upgrade `actions/upload-artifact` to v4 in GitHub Actions variant

---

variants/frontend-base/js-lint/template.rb

We released v4 of our config at the end of last year, which exports flat config by default unless the `ESLINT_USE_FLAT_CONFIG` environment variable is set to `false`.
While we want to upgrade to flat config and ESLint v9 ASAP, for now this just pins us to v3 to get CI passing again

fix: pin `eslint-config-ackama` to v3

---

variants/backend-base/README.md.tt
variants/backend-base/spec/spec_helper.rb
variants/code-annotation/template.rb
variants/github_actions_ci/workflows/ci.yml.tt

The original gem is no longer being maintained, and does not support Rails v8 properly - `annotaterb` is a fork that is well maintained, though has some differences which are covered in [the migration guide](https://github.com/drwl/annotaterb/blob/main/MIGRATION_GUIDE.md).
I have reviewed the default configuration and it looks to be the same except for these two properties:
```
:hide_default_column_types: '' # was "json,jsonb,hstore",
:hide_limit_column_types: '' # was "integer,bigint,boolean",
```
I suspect this is fine as I didn't see any change on my internal app, but I'm going to apply this to a few other apps first to double check - ideally I'd like to avoid having to have an `.annotaterb.yml` if we can avoid it

feat: replace `annotate` with `annotaterb`

---

variants/audit-logging/spec/services/audit_log_spec.rb

This ensures we're compatible with future versions of Ruby that have frozen strings enabled by default, and that currently trigger deprecation warnings when running on Ruby 3.4

fix: avoid mutating strings in audit log tests

---

template.rb
variants/backend-base/Gemfile.tt
variants/github_actions_ci/workflows/ci.yml.tt

The gem has standardized on `erb_lint`, and will remove support for the old `erblint` command in a future version

fix: migrate all usages of `erblint` to `erb_lint`

---

variants/backend-base/.erb_lint.yml
variants/backend-base/app/views/application/_flash.html.erb
variants/backend-base/app/views/application/_header.html.erb
variants/backend-base/app/views/application/analytics/_body.html.erb
variants/backend-base/app/views/application/analytics/_head.html.erb
variants/devise/template.rb

[Strict locals](https://guides.rubyonrails.org/action_view_overview.html#strict-locals) are a special comment that explicitly declares what local variables an ERB partial accepts, along with default values for when an optional variable is not present.
This improvements performance when dealing with large collections and applications by making partials monomorphic (rather than polymorphic, which can potentially turn megamorphic) resulting in them being compiled only once regardless of the variations in their parameters; otherwise, a new version of the partial has to be compiled for each different set of parameters they're rendered with.
Additionally, these comments make it easier to understand the partial and for both humans and tools to catch silly mistakes, since the comment defines …

feat: require all partials use strict locals

---

variants/frontend-base-typescript/.eslintrc.js
variants/frontend-react-typescript/.eslintrc.js
variants/frontend-stimulus-typescript/.eslintrc.js

This rule is turned off by our TypeScript config, since consuming TypeScript involves compiling it into native JavaScript which handles applying strict mode, but our config files are not compiled so we should ensure they explicitly enable strict mode

fix: re-enable `strict` lint rule for files that don't get compiled

---

template.rb
variants/accessibility/Gemfile.rb
variants/accessibility/spec/rails_helper.rb
variants/accessibility/spec/system/home_feature_spec.rb
variants/audit-logging/template.rb
variants/backend-base/Rakefile.rb
variants/backend-base/config.ru.rb
variants/backend-base/config/application.rb
variants/backend-base/config/environments/development.rb
variants/backend-base/config/environments/production.rb
variants/backend-base/config/environments/test.rb
variants/bullet/template.rb
variants/code-annotation/template.rb
variants/deploy_with_ackama_ec2_capistrano/template.rb
variants/deploy_with_capistrano/template.rb
variants/devise/template.rb
variants/frontend-base-typescript/template.rb
variants/frontend-base/js-lint/template.rb
variants/frontend-base/sentry/template.rb
variants/frontend-base/template.rb
variants/frontend-bootstrap/template.rb
variants/frontend-react-typescript/template.rb
variants/frontend-react/template.rb
variants/frontend-stimulus/template.rb
variants/github_actions_ci/template.rb
variants/pundit/template.rb
variants/sidekiq/template.rb

The file manipulation methods provided by Thor don't stop execution when they fail to do the defined manipulation, instead in our case they print an error but then proceed; we actually want to error in this situation since the whole point of our template is to be applying our preferred practices meaning its moot if we don't...
This really came into light with the Rails 8 upgrade which had a number of changes to the configuration files in particular that caused a number of our customizations to be skipped.
By introducing bang versions of the methods that error if the file contents does not change, we can ensure going forward all manipulations actually work; this uses the same logic I introduced in #533 for `gsub_file`, and caught a bug that I fixed in #596

fix: ensure that all file manipulations are applied

---

variants/devise/template.rb

I realised right after I landed #595 that I'd forgotten to double check after rebasing that I've replaced new usages of the file manipulation methods, but then as I was preparing this I _also_ realized that we're meant to be prepending the `locals` comments into the templates 🤦

fix(devise): prepend strict local hints to erb templates

---

variants/backend-base/config/initializers/content_security_policy.rb

This should help reduce the diff against future Rails upgrades, as the initializer they generate wraps everything in `Rails.application.configure`

refactor: use `Rails.application.configure` in CSP initializer

---

ci/bin/build-and-test
ci/bin/lint-configs.rb
variants/backend-base/config/environments/development.rb
variants/backend-base/config/environments/production.rb
variants/backend-base/config/environments/test.rb

This should make it easier to see changes when upgrading Rails and just generally make things abit cleaner by reducing the amount of code we've got

feat: reuse existing environment config comments to avoid doubling up

---

variants/backend-base/config/environments/production.rb

fix: reuse `config.assets.css_compressor` line in production config

---

template.rb
variants/accessibility/template.rb
variants/frontend-base-typescript/template.rb
variants/frontend-base/js-lint/template.rb
variants/frontend-base/sentry/template.rb
variants/frontend-base/template.rb
variants/frontend-bootstrap-typescript/template.rb
variants/frontend-bootstrap/template.rb
variants/frontend-react-typescript/template.rb
variants/frontend-react/template.rb
variants/frontend-stimulus-typescript/template.rb
variants/frontend-stimulus/template.rb

It's not longer a given that `yarn` is being used, and ultimately we're planning to switch to NPM so might as well change the method names now

refactor: rename methods for adding js dependencies to be more generic

---

variants/backend-base/rubocop.yml.tt

This started as just removing the `bin/*` since we've already got `bin/**/*` but I don't see a reason for us to exclude `doc/**/*` and `config/initializers/version.rb` 🤷
Ideally we should also include `bin/setup` but it doesn't seem like you can easily have Rubocop (re)include a single file so have left that for now

fix: don't exclude `doc/**/*` and `config/initializers/version.rb` from rubocops wrath

---

.rubocop.yml
variants/backend-base/rubocop.yml.tt

This was the default since Ruby 3.1 but turns out a year ago [they changed it to "either"](https://github.com/rubocop/rubocop/pull/13300) - since we already decided we're in favor of using this syntax when the rule originally came out, and I don't think there's any value in using it conditionally, this has Rubocop enforce it again

feat: have Rubocop always enforce shorthand hash syntax

---

variants/accessibility/spec/rails_helper.rb
variants/github_actions_ci/workflows/ci.yml.tt

The newest version of [`lighthouse-matchers` has audit results written to disk](https://github.com/ackama/lighthouse-matchers/pull/68) to make it easier to debug why a score was lower than expected, so this has our standard CI capture those in the rspec output artifacts, along with capybara screenshots

feat: have ci capture capybara screenshots and lighthouse results in rspec output artifact
