- .travis.yml
- template-test/ci-run.sh
- template.rb
- variants/frontend-base/app/template.rb
- variants/frontend-base/config/template.rb
- variants/frontend-base/template.rb
- variants/frontend-foundation/app/frontend/foundation/_settings.scss
- variants/frontend-foundation/app/frontend/foundation/application.scss
- variants/frontend-foundation/app/frontend/foundation/base/base.scss
- variants/frontend-foundation/app/frontend/foundation/base/buttons.scss
- variants/frontend-foundation/app/frontend/foundation/base/containers.scss
- variants/frontend-foundation/app/frontend/foundation/base/forms.scss
- variants/frontend-foundation/app/frontend/foundation/index.js
- variants/frontend-foundation/template.rb
Adds a new variant that will generate Foundation SASS modules in the `app/frontend` directory.
This PR also introduces functionality to request whether a particular variant should be provisioned, including checking an environment variable. This allows the bootstrapping of an application to be sped up by passing a list of variants which the person generating the new application wishes to apply.
Outstanding tasks:
[ ] Apply frontend-base when foundation is applied
[ ] Fix build
The next PR after this one will add optional navigation and header components to Foundation.
> Variant: Frontend Foundation

- config/environments/production.rb
> Set production log level to :info

- README.md.tt
> Add prettier compatible version of standard Ackama README template.

- template.rb
> Remove unused test/ directory

- .travis.yml
I'll start by sending these to #platforms-debug in case they are too noisy. If we like them we can move them to a real channel.
> Add slack notifications from TravisCI

- README.md
- README.md.tt
> 📝 Readme updates

- .eslintignore
- .eslintignore.tt
> fix: add `bundle/` to `.eslintignore`

- variants/frontend-foundation-layout/app/frontend/foundation/components/header.js
> Prettier changed it's mind and was breaking builds

- variants/frontend-foundation-layout/app/views/application/header/_navigation.html.erb
Fixes issue #74 . Turns out the fix was straightforward :smile:
> Fix failing lighthouse accessibility tests

- Gemfile.tt
- rubocop.yml.tt
- spec/helpers/retina_image_helper_spec.rb
- spec/requests/health_checks_spec.rb
- variants/devise/spec/models/user_spec.rb
- variants/devise/spec/system/user_reset_password_feature_spec.rb
- variants/devise/spec/system/user_sign_in_feature_spec.rb
> Add rubocop-rspec to the default generated Rails app

- variants/devise/spec/factories/users.rb
- variants/devise/spec/models/user_spec.rb
- variants/devise/spec/system/user_reset_password_feature_spec.rb
- variants/devise/spec/system/user_sign_in_feature_spec.rb
- variants/devise/spec/system/user_sign_up_feature_spec.rb
- variants/devise/template.rb
* turn on "paranoid" mode in devise
* change the minimum password length to 16 chars
* enable `lockable` module by default
It addresses three issues:
* fixes #87
* fixes #88
* fixes #89
> This change improves the security of our default devise setup.

- Gemfile.tt
- config/initializers/sentry.rb
- config/template.rb
- example.env.tt
- template.rb
- variants/frontend-base/template.rb
* Add Sentry https://github.com/getsentry/raven-ruby
* Create `.env` by default. We need a `.env` file to store the Sentry DSN.
Closes #92
> Add Sentry and configure it

- spec/rails_helper.rb
- variants/devise/spec/models/user_spec.rb
- variants/devise/spec/requests/session_cookie_expiry_spec.rb
- variants/devise/spec/system/user_reset_password_feature_spec.rb
- variants/devise/spec/system/user_sign_in_feature_spec.rb
- variants/devise/spec/system/user_sign_up_feature_spec.rb
~(I'll squash this on merge)~ 🥭
> chore: fix linting errors

- Gemfile.tt
- example.env.tt
- variants/devise/template.rb
These issues were found and fixed in the project by @OBaddeley - I'm just reflecting the fixes back to the template for future us.
> Fix issues discovered using this on a project

- README.md
Fix https://github.com/ackama/rails-template/issues/183
Add explanation for react variant in readme
> Add explanation for react variant

- app/views/layouts/application.html.erb.tt
https://github.com/ackama/rails-template/issues/185
fix out form `origin-when-crossorigin` to `origin-when-cross-origin`
> referer-policy

- config/environments/production.rb
> fix: make rubocop happy

- .github/workflows/ci.yml
Completely missed this when reviewing #182, so we've been testing against the wrong variants every since 😬
> Test react variant

- .github/workflows/ci.yml
I really wish :lolsob: was an official emoji...
> ci: add missing n characters to `\n`s

- package.json
- variants/frontend-base/js-lint/template.rb
- yarn.lock
Tis' a small thing, but I like the consistency, especially given all you've got to do is install the plugin and `prettier` will pick it up 🎉
> feat: add `prettier-plugin-packagejson`

- .auditapprc.json
This has been patched in the latest version of lighthouse 🎉
> fix: remove patched vulnerability from ignore list

- template.rb
- variants/frontend-audit-app/template.rb
- variants/frontend-base/js-lint/template.rb
> feat: generate `.auditapprc.json` dynamically

- template.rb
- variants/accessibility/template.rb
- variants/frontend-base/js-lint/template.rb
- variants/frontend-base/sentry/template.rb
- variants/frontend-foundation/template.rb
- variants/frontend-typescript/template.rb
Makes it easier to add/remove/adjust the packages we're installing.
> refactor: list yarn packages to make them easier to read and edit

- config/application.rb
Added recommended custom header to opt out of of Google FLoC user tracking.
> Added custom header to opt out of Google FLoC user tracking

- Gemfile.tt
Closes issue #292 (more context in the issue if you need it)
Our starter Gemfile was getting a bit crufty. 
I discussed the approach in person with @joshmcarthur. Details in comments.
> Update Gemfile to more closely match Rails7 defaults

- config/initializers/check_env.rb
- config/template.rb
- variants/frontend-bootstrap/template.rb
> Ensure secret key isn't reused from the one in example.env

- template.rb
- variants/frontend-bootstrap/app/frontend/stylesheets/customized_bootstrap.scss
- variants/frontend-bootstrap/template.rb
See https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/#new-_mapsscss
Fixes #315
> fix: import default scss bootstrap `maps`

- template.rb
> Add x86_64-linux platform to Gemfile.lock

- variants/sidekiq/template.rb
> Sidekiq variant enables OkComputer checks for Redis and Sidekiq queues

- variants/frontend-base/sentry/template.rb
- variants/frontend-typescript/template.rb
I'm pretty sure we can remove this now 🤞
> fix: use latest version of `dotenv-webpack` plugin

- spec/spec_helper.rb
> test: enable branch coverage tracking

- .rubocop.yml
- rubocop.yml.tt
> Define assert_match as an expectation

- Gemfile.tt
- spec/spec_helper.rb
This is not a fix for issue #375 but it keeps us generating working apps while we work on #375
Closes #377
> Lock puma to 5.x for now until we can properly support puma 6+

- variants/github_actions_ci/workflows/ci.yml.tt
> Run type checking before JS linting in CI if Typescript enabled

- .stylelintignore
> Remove unused stylelint ignore file

- variants/backend-base/README.md.tt
I have removed references to specific browsers and versions because it is too project specific. The new wording is more generic but will hopefully remain true into the future and provide a useful starting point for devs.
> Modernise our default browser support requirements

- yarn.lock
> fix: upgrade `minimatch` for security

- variants/frontend-react-typescript/jest.config.ts
https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#deprecations-1
> fix: adjust jest config to avoid deprecation

- variants/backend-base/README.md.tt
- Taken from another project
- passed README js checks in that branch
- this pull requested by @G-Rath
> README: naming-conventions link relates to deployment

- .github/workflows/ci.yml
- ackama_rails_template.config.yml
> feat: enable TypeScript variants by default

- variants/backend-base/spec/rails_helper.rb
previously if you had HTTP_BASIC_AUTH_USERNAME & HTTP_BASIC_AUTH_PASSWORD defined, all the bulit in tests would fail. #426 was my first solution but that's so unnecessary complicated, this pr probably doesn't even need the tests
> Keep tests passing if you have basicauth

- .rubocop.yml
- variants/backend-base/rubocop.yml.tt
As discussed in Ruby guild this morning.
> fix: change `Layout/FirstHashElementIndentation` to be `consistent`

- .rubocop.yml
- ci/bin/build-and-test
- template.rb
- variants/backend-base/app/controllers/active_storage/base_controller.rb
- variants/backend-base/config/initializers/check_env.rb
- variants/backend-base/rubocop.yml.tt
> refactor: prefer to always use `raise`

- variants/frontend-base/app/frontend/stylesheets/_reset.scss
- variants/frontend-base/app/frontend/stylesheets/application.scss
- variants/frontend-base/template.rb
Following on from our discussions at frontend guild, we're proceeding with the creation of a minimal CSS reset that handles `box-sizing`. This file is free to evolve over time with additional declarations as we see fit.
> feat: A simple `box-sizing` reset

- .rubocop.yml
- variants/backend-base/rubocop.yml.tt
Details: https://github.com/rubocop/rubocop-rails/issues/681
Closes #490
> Disable Rails/SqishedSQLHeredocs because it breaks some kinds of raw SQL

- variants/backend-base/Gemfile.tt
- variants/backend-base/config/puma.rb
> Upgrade puma

- README.md
- template.rb
- variants/backend-base/.erb-lint.yml
- variants/backend-base/Gemfile.tt
- variants/github_actions_ci/workflows/ci.yml.tt
> Add erblint to lint ERB and run Rubocop on Ruby embedded in ERB

- variants/backend-base/spec/rails_helper.rb
https://guides.rubyonrails.org/7_1_release_notes.html#active-record-deprecations
> fix: use `fixture_paths`

- variants/github_actions_ci/workflows/ci.yml.tt
These are needed to boot with our current secrets template
> Define encryption keys for ci env

- variants/github_actions_ci/workflows/ci.yml.tt
Looks like this has been missing from the start 😬
> fix: run stylelint as part of CI

- variants/deploy_with_ackama_ec2_capistrano/template.rb
- variants/deploy_with_capistrano/template.rb
I'm pretty sure I've never used this ever, nor do I recall seeing anyone else use it so maybe we should just remove it?
> feat: remove `capistrano-rake`

- variants/backend-base/config/puma.rb
Currently we've got two slightly different implementations of the same check/logic, which is silly 😅
> refactor: cleanup puma config

- .github/workflows/ci.yml
> ci: capture variant failure outputs as artifacts
